### PR TITLE
Button customization. Boilerplate addon

### LINKED ISSUE #1: Color options
On some dark sites, the button is not as visible, i.e. http://www.avren.co.il/.

### PR DESCRIPTION
**Pull request by GirlBossRush**
This PR adds several new options; color, icon, and shape.

https://eager.io/developer/app-tester?ref=github.com/EagerApps/BackToTopButton@dev

Closes #1

### CODE REVIEW

**Comment by adamschwartz** [comment]
Such a good implementation. Really awesome.

A few things I thought of:
- This is such a cool way to handle the colors: 
  image
  
  The auto implementation is really solid, but as a quicker option for some folks who don’t want to pick a color, how about adding two more bullets between the two called “Dark” and “Light” which are just `#000000` and `#ffffff` respectively. (Could also be called “Black” and “White” if you think that makes more sense.)
- I thought of an interesting way to handle loading the SVGs. Since each icon contains only one path object with one `d` attribute, why don’t we just use `d` values as the three string values for the three choices in the `install.json` file. 😛 
- The color logic for the auto option is really cool, but I think we should try to trim the size of the color lib. Looking quickly it seems like we only use the constructor and the `toHSL` method, and we can assume a hex input from `install.json`. Given that I think we should be able to slim the lib down a ton and I think we should: as this app is proportionally not that crucial to a website I think it becomes even more important (than it is for Eager apps in general) to focus on payload size.
- ~~Lastly, it’s a minor thing, but I’m curious if you intended the button to move slightly down on `:active`? I think it’s kind of cool but I wanted to make sure it was intended.~~ nvm it obviously was; nice job! 😄

**Comment by adamschwartz** [comment]
Incidentally, re:

> - The color logic for the auto option is really cool, but I think we should try to trim the size of the color lib. Looking quickly it seems like we only use the constructor and the toHSL method, and we can assume a hex input from install.json. Given that I think we should be able to slim the lib down a ton and I think we should: as this app is proportionally not that crucial to a website I think it becomes even more important (than it is for Eager apps in general) to focus on payload size.

I think this is especially a cool idea because it means that the icon is then a configuration for the library, allowing a user to supply their own `d` theoretically. e.g. If we ever felt it necessary we could have a “Custom” icon option which would `showIf` a string field asking the installer to supply a path `d` attribute. Or if this lib got traction outside of Eager, etc.

**Comment by adamschwartz** [comment]
Oh one more small thing. I would change the “Color” label on the install JSON object to “Background color” and then add `"notitle": true` to the strategy choice.

image

**Comment by zackbloom** [comment]
Minor comment, the copy on the color option:

screen shot 2016-07-12 at 12 36 48 pm

It's a bit odd (but not crazy) to have Color and then Background color inside of it, but I do think you need to specify the background of what.  I know it should be obvious given you are inserting a button, but I think being explicit about 'Button Background Color' would make sense.  Even better though, given it's the only color you can set, why not just call it the Color?  And maybe move the color and color toggle out of a properties block so you don't have to give them an extra title?

UPDATE: Lol, Adam and I commented at exactly the same time.

**Comment by adamschwartz** [comment]
After reading @zackbloom’s let’s just `notitle` the strategy choice but leave “Color” as is.

**Pull request merged**
